version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
    - requirements: source/requirements.txt