version: 2

sphinx:
  builder: html
  configuration: source/conf.py
  fail_on_warning: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

formats:
  - pdf

python:
  install:
    - requirements: source/requirements.txt
